# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624c8fdcd6df98f90959a172a3f64d37100795c96dbd378d6671a7875d9a86ee3f60c664a1ee7fe79b59786190ab86feec7b61efaed26e9bae9915ea98613c9b

test:
  secret_key_base: 40fe6dd841f33920398bc87f4cd5511e2eb95d21c4cfbb4f60227721d25faf19a0fe4f4c30d69779bdd8af4939c9770e28a564db7b6f4013350f8dcd217f7aa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
